### ISSUE TITLE
our buddy, protobuf, is causing problems again

### ISSUE THREAD

**Issue by cfregly** [tjhunter/tensorframes#31]
example zeppelin notebook:  http://demo.pipeline.io:8080/#/notebook/2BNQNXKH5

getting the following error:
```
java.lang.VerifyError: class org.tensorflow.framework.AttrValue$Builder overrides final method mergeUnknownFields.(Lcom/google/protobuf/UnknownFieldSet;)Lcom/google/protobuf/GeneratedMessage$Builder;
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.tensorflow.framework.AttrValue.toBuilder(AttrValue.java:3085)
	at org.tensorflow.framework.AttrValue.newBuilder(AttrValue.java:3079)
	at org.tensorframes.dsl.DslImpl$ShapeToAttr.toAttr(DslImpl.scala:21)
	at org.tensorframes.dsl.DslImpl$.placeholder(DslImpl.scala:86)
	at org.tensorframes.dsl.DslImpl$.extractPlaceholder(DslImpl.scala:104)
	at org.tensorframes.dsl.package$.block(package.scala:97)
	at org.tensorframes.dsl.DFImplicits$RichDataFrame.block(Implicits.scala:96)
...
```

spark 1.6.1, TENSORFRAMES_VERSION=0.2.2

all versions of everything can be found here:  https://github.com/fluxcapacitor/pipeline/blob/master/Dockerfile

starting zeppelin with the following

```
# --repositories used to resolve --packages
export SPARK_REPOSITORIES=http://dl.bintray.com/spark-packages/maven,https://oss.sonatype.org/content/repositories/snapshots,https://repository.apache.org/content/groups/snapshots

# --packages used to pass into our Spark jobs
export SPARK_SUBMIT_PACKAGES=tjhunter:tensorframes:$TENSORFRAMES_VERSION-s_2.10,amplab:spark-indexedrdd:$INDEXEDRDD_VERSION,org.apache.spark:spark-streaming-kafka-assembly_2.10:$SPARK_VERSION,org.elasticsearch:elasticsearch-spark_2.10:$SPARK_ELASTICSEARCH_CONNECTOR_VERSION,com.datastax.spark:spark-cassandra-connector_2.10:$SPARK_CASSANDRA_CONNECTOR_VERSION,redis.clients:jedis:$JEDIS_VERSION,com.twitter:algebird-core_2.10:$ALGEBIRD_VERSION,com.databricks:spark-avro_2.10:$SPARK_AVRO_CONNECTOR_VERSION,com.databricks:spark-csv_2.10:$SPARK_CSV_CONNECTOR_VERSION,org.apache.nifi:nifi-spark-receiver:$SPARK_NIFI_CONNECTOR_VERSION,com.madhukaraphatak:java-sizeof_2.10:0.1,com.databricks:spark-xml_2.10:$SPARK_XML_VERSION,edu.stanford.nlp:stanford-corenlp:$STANFORD_CORENLP_VERSION,org.jblas:jblas:$JBLAS_VERSION,graphframes:graphframes:$GRAPHFRAMES_VERSION

# We still need to include a reference to a local stanford-corenlp-$STANFORD_CORENLP_VERSION-models.jar because SparkSubmit doesn't support a classifier in --packages
export SPARK_SUBMIT_JARS=$MYAPPS_HOME/codegen/spark/1.6.1/target/scala-2.10/codegen-spark-1-6-1_2.10-1.0.jar,$MYAPPS_HOME/spark/redis/lib/spark-redis_2.10-$SPARK_REDIS_CONNECTOR_VERSION.jar,$MYSQL_CONNECTOR_JAR,$MYAPPS_HOME/spark/ml/lib/spark-corenlp_2.10-0.1.jar,$MYAPPS_HOME/spark/ml/lib/stanford-corenlp-$STANFORD_CORENLP_VERSION-models.jar,$MYAPPS_HOME/spark/ml/target/scala-2.10/ml_2.10-1.0.jar,$MYAPPS_HOME/spark/sql/target/scala-2.10/sql_2.10-1.0.jar,$MYAPPS_HOME/spark/core/target/scala-2.10/core_2.10-1.0.jar,$MYAPPS_HOME/spark/streaming/target/scala-2.10/streaming_2.10-1.0.jar
```

**Comment by tjhunter** [comment]
@cfregly I am very surprised that you are getting this error, because this problem cannot happen in the  official 0.2.2 release.

According to the released code in
 http://dl.bintray.com/spark-packages/maven/tjhunter/tensorframes/0.2.2-s_2.10/tensorframes-0.2.2-s_2.10.jar ,
the signature of the method you are mentioning is explicitly shaded (see disassembly below):
```
public org.tensorframes.protobuf3shade.Message$Builder mergeUnknownFields(org.tensorframes.protobuf3shade.UnknownFieldSet);
```

I suspect you have compiled the code yourself. If you want to go this route, do not use `spDist`. You must use `tfPackage` or `assembly` instead. I am going to close this bug for now, but feel free to reopen it if it turns out that the file loaded by zeppelin is the correct file (then it may be an issue with zeppelin).

**Comment by cfregly** [comment]
@tjhunter thanks for the response.  i started fresh from with clean docker image - and things seem to be working now.

i had a heavily-modified version of my stock [fluxcapacitor/pipeline](https://github.com/fluxcapacitor/pipeline) environment running at the time, so it could have been anything.

i don't *think* i built it from scratch as the only version of TensorFrames known to spark/zeppelin was the one in the SPARK_SUBMIT_PACKAGES env variable, but who knows.  software is a mystery, right?!

thanks for highlighting the shaded library.  the world is a better place in the shade.
